[package]
name = "chip8-rust"
version = "0.1.0"
authors = ["Isaac Asensio <isaac.asensio@gmail.com>"]

[dependencies]
rand = "0.4"

[lib]
name = "chip8"
path = "src/lib.rs"

[[bin]]
name = "chip8"
path = "src/main.rs"