[package]
name = "chip8-rust"
version = "0.1.0"
authors = ["Isaac Asensio <isaac.asensio@gmail.com>"]

[dependencies]

[lib]
name = "chip8"
path = "src/executor.rs"

[[bin]]
name = "chip8"
path = "src/main.rs"